[tool.poetry]
name = "ai-classifier"
version = "0.1.0"
description = "Your project description"
authors = ["Your Name <your@email.com>"]

[tool.poetry.dependencies]
python = "^3.10.12"
flask = "^2.0.0"
# أضف باقي المكتبات هنا

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"